### ISSUE TITLE
Always On Failover Availability Group Automation 

### ISSUE THREAD

**Issue by sfnemis** [rafaelrodrigues3092/docker-mssql-alwayson#1]
Hi!

I have successfully installed the always-on system from your current repository, and I want to thank you for that. However, while the primary database is inaccessible, I want to be able to write to and update the secondary database. In other words, how can I automatically make the secondary database the primary one in this situation? Is it possible to set up such an architecture?

**Comment by rafaelrodrigues3092** [comment]
Hi @sfnemis 

In this type of setup you can only achieve what you are looking for via a manual forced failover.
This can be done by running the following query on the secondary replica:
`ALTER AVAILABILITY GROUP AG1 FORCE_FAILOVER_ALLOW_DATA_LOSS;`.
In this project, I also included a SQL Server Agent job named `FAILOVER - AG1` which you can run on the secondary replica to force the failover.


This setup consists of [CLUSTER_TYPE = NONE](https://learn.microsoft.com/en-us/sql/database-engine/availability-groups/windows/specify-availability-group-name-page?view=sql-server-ver16#cluster-type-dropdown-list) which sets up the SQL Server availability group in a [read scale mode](https://learn.microsoft.com/en-us/sql/database-engine/availability-groups/windows/read-scale-availability-groups?view=sql-server-ver16) where automatic failover is not possible.
To have automatic failover, you need a cluster heartbeat either from a Windows cluster or something external like pacemaker in Linux.

I hope that helps.
